"use strict";

// Generated by CoffeeScript 2.5.1
(function () {
  var fill;

  fill = function fill(container) {
    var liquid = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : "coffee";
    return "Filling the ".concat(container, " with ").concat(liquid, "...");
  };

  module.exports = fill;
}).call(void 0);